name: 'Changelog Generator'
description: 'Automatically generate changelogs from PR descriptions'
author: 'Your Name'

inputs:
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  pr_number:
    description: 'Pull request number'
    required: true
  repo:
    description: 'Repository name (e.g. owner/repo)'
    required: true
    default: ${{ github.repository }}
  changelog_dir:
    description: 'Directory to store changelog files'
    required: false
    default: 'changelog'
  client_subdirectory:
    description: 'Subdirectory for client-facing changelogs'
    required: false
    default: 'client'
  internal_subdirectory:
    description: 'Subdirectory for internal changelogs'
    required: false
    default: 'internal'
  unified_changelog:
    description: 'Use a single changelog instead of separate types'
    required: false
    default: 'false'
  unified_format:
    description: 'Format to use for unified changelog (client or internal)'
    required: false
    default: 'client'
  single_file:
    description: 'Use a single file for all versions'
    required: false
    default: 'false'
  single_filename:
    description: 'Filename to use for single file mode'
    required: false
    default: 'CHANGELOG.md'
  include_date_in_version:
    description: 'Include date in version headers'
    required: false
    default: 'true'
  date_format:
    description: 'Format for dates'
    required: false
    default: '%Y-%m-%d'
  commit_changes:
    description: 'Whether to commit changes to the repo'
    required: false
    default: 'true'
  commit_message:
    description: 'Commit message for changelog updates'
    required: false
    default: 'Update changelog for PR #{pr_number}'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    PR_NUMBER: ${{ inputs.pr_number }}
    REPO_NAME: ${{ inputs.repo }}
    CHANGELOG_DIR: ${{ inputs.changelog_dir }}
    CLIENT_SUBDIR: ${{ inputs.client_subdirectory }}
    INTERNAL_SUBDIR: ${{ inputs.internal_subdirectory }}
    UNIFIED_CHANGELOG: ${{ inputs.unified_changelog }}
    UNIFIED_FORMAT: ${{ inputs.unified_format }}
    SINGLE_FILE: ${{ inputs.single_file }}
    SINGLE_FILENAME: ${{ inputs.single_filename }}
    INCLUDE_DATE_IN_VERSION: ${{ inputs.include_date_in_version }}
    DATE_FORMAT: ${{ inputs.date_format }}
    COMMIT_CHANGES: ${{ inputs.commit_changes }}
    COMMIT_MESSAGE: ${{ inputs.commit_message }}

branding:
  icon: 'book-open'
  color: 'blue'